USE airline_delay_diagnostic;

SELECT
    TAIL_NUMBER,
    YEAR, MONTH, DAY,
    FLIGHT_NUMBER,
    SCHEDULED_DEPARTURE,
    ARRIVAL_DELAY,
    LAG(ARRIVAL_DELAY) OVER (
        PARTITION BY TAIL_NUMBER, YEAR, MONTH, DAY
        ORDER BY SCHEDULED_DEPARTURE
    ) AS PREV_FLIGHT_ARRIVAL_DELAY,
    DEPARTURE_DELAY
FROM flights
WHERE TAIL_NUMBER IS NOT NULL
ORDER BY TAIL_NUMBER, YEAR, MONTH, DAY, SCHEDULED_DEPARTURE
LIMIT 100;
WITH flight_chain AS (
    SELECT
        TAIL_NUMBER, YEAR, MONTH, DAY, FLIGHT_NUMBER,
        SCHEDULED_DEPARTURE, DEPARTURE_DELAY, ARRIVAL_DELAY,
        LAG(ARRIVAL_DELAY) OVER (
            PARTITION BY TAIL_NUMBER, YEAR, MONTH, DAY
            ORDER BY SCHEDULED_DEPARTURE
        ) AS PREV_ARRIVAL_DELAY
    FROM flights
    WHERE TAIL_NUMBER IS NOT NULL
)
SELECT
    CASE
        WHEN PREV_ARRIVAL_DELAY IS NULL THEN 'First flight of the day'
        WHEN PREV_ARRIVAL_DELAY > 15 THEN 'Previous flight delayed >15 min'
        ELSE 'Previous flight on-time'
    END AS prior_flight_status,
    COUNT(*) AS num_flights,
    ROUND(AVG(DEPARTURE_DELAY), 2) AS avg_departure_delay
FROM flight_chain
GROUP BY prior_flight_status;