USE airline_delay_diagnostic;

SELECT
    CASE
        WHEN FLOOR(SCHEDULED_DEPARTURE / 100) BETWEEN 5 AND 8 THEN '1. Early Morning (5-9AM)'
        WHEN FLOOR(SCHEDULED_DEPARTURE / 100) BETWEEN 9 AND 11 THEN '2. Morning (9AM-12PM)'
        WHEN FLOOR(SCHEDULED_DEPARTURE / 100) BETWEEN 12 AND 16 THEN '3. Afternoon (12-5PM)'
        WHEN FLOOR(SCHEDULED_DEPARTURE / 100) BETWEEN 17 AND 20 THEN '4. Evening (5-9PM)'
        ELSE '5. Night (9PM-5AM)'
    END AS time_of_day,
    COUNT(*) AS num_flights,
    ROUND(AVG(DEPARTURE_DELAY), 2) AS avg_departure_delay,
    ROUND(AVG(CASE WHEN DEPARTURE_DELAY > 15 THEN 1 ELSE 0 END) * 100, 1) AS pct_delayed_over_15min
FROM flights
WHERE SCHEDULED_DEPARTURE IS NOT NULL
GROUP BY time_of_day
ORDER BY time_of_day;
SELECT
    CASE
        WHEN FLOOR(SCHEDULED_DEPARTURE / 100) BETWEEN 5 AND 8 THEN '1. Early Morning (5-9AM)'
        WHEN FLOOR(SCHEDULED_DEPARTURE / 100) BETWEEN 9 AND 11 THEN '2. Morning (9AM-12PM)'
        WHEN FLOOR(SCHEDULED_DEPARTURE / 100) BETWEEN 12 AND 16 THEN '3. Afternoon (12-5PM)'
        WHEN FLOOR(SCHEDULED_DEPARTURE / 100) BETWEEN 17 AND 20 THEN '4. Evening (5-9PM)'
        ELSE '5. Night (9PM-5AM)'
    END AS time_of_day,
    ROUND(AVG(LATE_AIRCRAFT_DELAY), 2) AS avg_late_aircraft_delay_minutes
FROM flights
WHERE SCHEDULED_DEPARTURE IS NOT NULL
GROUP BY time_of_day
ORDER BY time_of_day;